# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from .._models import BaseModel
from .shared.content import Content

__all__ = ["CompletionResponse", "Choice", "ChoiceMessage"]


class ChoiceMessage(BaseModel):
    content: str
    """The content of the message"""

    role: Literal["assistant"]
    """The role of the message sender"""


class Choice(BaseModel):
    finish_reason: str
    """The reason why the model stopped generating tokens"""

    index: int
    """The index of this completion choice"""

    message: ChoiceMessage

    citations: Optional[List[Content]] = None
    """Array of search results"""


class CompletionResponse(BaseModel):
    choices: List[Choice]
    """The completion choices generated by the model"""

    created: int
    """The Unix timestamp (in seconds) of when the completion was created"""
